# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0002_auto_20180531_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reserve.Profile'),
        ),
    ]
