# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0003_restaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=40)),
                ('food_image', models.ImageField(blank=True, upload_to='images/')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reserve.Restaurant')),
            ],
        ),
    ]
