# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reserve.Profile'),
        ),
    ]
