# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0007_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
    ]
