# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0008_auto_20180603_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reserve.Menu'),
        ),
    ]
